# Generated by Django 3.2.3 on 2021-05-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.location')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
    ]
